name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        uses: actions/checkout@v2
      - name: Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install
      - name: Configure name and email (GIT)
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Build project
        run: bundle exec jekyll build -d docs-tmp
      - name: Deploy project
        run: |
          git --work-tree docs-tmp add --all
          git --work-tree docs-tmp commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
